### ISSUE TITLE
file limitation more than 130 kb ?

### ISSUE THREAD

**Issue by mms-mMarconi** [Chris2011/js-css-minify-compress#15]
With javascript source files of more than 130 kb, the output (minifyed file) is empty.

**Comment by jGauravGupta** [comment]
Please attach the sample javascript file.

**Comment by Chris2011** [comment]
@mms-mMarconi please attach the file or a similar one. If there is an exception with syntax error, that it is related to #3

**Comment by Chris2011** [comment]
Please test version 2.4.0.
