### ISSUE TITLE
Bundle css/js Files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Chris2011/js-css-minify-compress#2]
```
Hey,

many thanks to you for your tool, but i need bundling js/css files.

Is that possible to bundling minified files? eg. with an instruction comment 
like that:

+++++++++++ bundles.js ++++++++
#import ./../myJSFiles/file1.js
#import ./../myJSFiles/file2.js

function fooBar()
{
    alert("very nice");
}
+++++++++++++++++++++++++++++++
```

Original issue reported on code.google.com by `majectm...@gmail.com` on 10 Apr 2014 at 3:26

**Comment by Chris2011** [comment]
Is this a common behaviour in other IDEs? I don't know atm.

**Comment by Chris2011** [comment]
What you want is concatination, but I don't know whether this can be handled with the closure compiler. I will close it, because it is not relevant anymore. IMHO. Reopen it, if you think so.
