### ISSUE TITLE
Minified HTML is wrong

### ISSUE THREAD

**Issue by Ilya-Zhulin** [Chris2011/js-css-minify-compress#29]
Hi. I use this plugin very active, but exclude HTML minify - it's impossible to use it without "copyright header" setting. In the rules HTML document must start with ```<!DOCTYPE html>``` tag, not from my header. But, if I keep this field empty, I have ```null``` text in start of document. Please, @Chris2011, correct this option - make it optioanally, or just make that empty field is not "null", but empty string (nothing).
It would be the best to check is there Doctype tag in the document, and if there is to put comment after it.
Thanks!

**Comment by Chris2011** [comment]
Can you please attach a simple sample of your HTML file how does it looks and how does the outputted file looks like?

**Comment by krheinwald** [comment]
Either a blank line is inserted at beginning of the minified HTML, or 'null' after fiddling with the options. Not really sure what triggers - only a restart helps afterwards.

**Comment by Chris2011** [comment]
w/o detailed steps I can't reproduce it. how? Please attach the HTML file, where this happens or give more me more steps. Thx.
