### ISSUE TITLE
Detailed Syntax Errors not Shown on Minifiying JS

### ISSUE THREAD

**Issue by nigelnquande** [Chris2011/js-css-minify-compress#31]
When minifying JS, the minification process sometimes results in syntax errors due to questionable JS syntax/code. This is understandable. What is annoying is the minifier doesn't state what code caused errors, just that errors were encountered. 

It'd be useful if for each error, there would be a message stating what line and char (approximately) in the original file contained the error, so that it can be rectified and minification rerun.

**Comment by Chris2011** [comment]
Please attach the JS or pieces of it, what you want to minify and attach the errors. Thx. In general you should see, what is the problem. And as I wrote on the Readme, you can test the code online: http://refresh-sf.com/.

**Comment by nigelnquande** [comment]
Having used YUI compressor (which provides detailed output), it determined that the issue was one of using keywords or reserved words as object properties in the form of `object.property` instead of `object['property']`. A message such as the following would have been useful:

"Errors were encountered during minification. Please check that the code does not use keywords or reserved words as object properties."

**Comment by Chris2011** [comment]
As I said; oklease attach the JS or pieces of it, what you want to minify and attach the error/stack trace. I think you have a bit more then object.property. Thx.

**Comment by Chris2011** [comment]
Closing as invalid, because of missing code to test.
