### ISSUE TITLE
ES6 Class isn't minified.

### ISSUE THREAD

**Issue by hkaraoglu** [Chris2011/js-css-minify-compress#32]
If there is an ES6 class in javascript file. It isn't minified. The plugin just creates an empty file.

**Example code:**

```
class Polygon {
  // ..and an (optional) custom class constructor. If one is
  // not supplied, a default constructor is used instead:
  // constructor() { }
  constructor(height, width) {
    this.name = 'Polygon';
    this.height = height;
    this.width = width;
  }

  // Simple class instance methods using short-hand method
  // declaration
  sayName() {
    ChromeSamples.log('Hi, I am a ', this.name + '.');
  }

  sayHistory() {
    ChromeSamples.log('"Polygon" is derived from the Greek polus (many) ' +
      'and gonia (angle).');
  }

  // We will look at static and subclassed methods shortly
}
```

**Output:**

Empty file.

**Comment by Chris2011** [comment]
Hi, thx for the report. Please read my readme from the Headline Attention. This plugin uses yuicompressor and unfortunately it is not supporting ES6. Thx

**Comment by Chris2011** [comment]
Duplicate of #3

**Comment by jGauravGupta** [comment]
Possibly yuicompressor  can be replaced with ES6 supported compressor.

**Comment by Chris2011** [comment]
yes I thought so too but unfortunately this is not on prio list :/

**Comment by hkaraoglu** [comment]
At least, this issue can be solved by creating an output file is as same as input file instead of empty file.

**Comment by Chris2011** [comment]
As an easy workaround and a message, what happens there. To create the same output after minifing is confusing, the same as the current behaviour. So a little message like: There where errors, we can't minified it, would be better and to generate the file anyway or not. With an option. But as I said, this could be the workaround for this.

The better solution, maybe for an other ticket is to get rid of the YUI Compressor and use a updated one, like the google closure compiler or what we have.

**Comment by hkaraoglu** [comment]
Fixed by creating same output file if a file is cannot be minified. (Workaround.)
