### ISSUE TITLE
null is rendered at the first line in JS when header field is left blank

### ISSUE THREAD

**Issue by jepsar** [Chris2011/js-css-minify-compress#34]
When I enter something like `//` in the header field, it is reflected on the first line.

Might relate to #14

**Comment by Chris2011** [comment]
Hey @jepsar can you please be more specific and maybe give a code sample? Will check it. Thx. I moved from YUICompressor to googl closure compiler. Maybe it will be fixed due to the switch but, to less information for that.

**Comment by Chris2011** [comment]
Test code:

```javascript
// Test.
```

Output:
```javascript
'use strict';
```

So I couldn't see any problems here, only that it will always added use strict, but this will be another issue. So it seems to be fixed in 2.4.0.
