### ISSUE TITLE
It doesn´t support back-tick symbol (`  `) it is used in string template javascript.

### ISSUE THREAD

**Issue by Pikdo** [Chris2011/js-css-minify-compress#40]
Hi 
It doesn´t support back-tick symbol (`  `) it is used in string template javascript, my minify-compress process fail and .min get blank.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Thanks

**Comment by Chris2011** [comment]
Please read the readme file from the beginnging. Everything is written at this place. In short, there is no ES6 support for yuicompressor.

**Comment by Pikdo** [comment]
Thanks, maybe later it can be ES6 sintax support.

**Comment by Chris2011** [comment]
For the YUICompressor, In my opinion, I don't think so. This plugin is dependent from YUICompressor and when you follow the repo of it, it is kind of unmaintained. No real progress anymore. So the only option is to get rid of the errors. There is a PR from a contributor, where we can have a release soon, but this is only a workaround and will not solve the problem. Or should get rid of YUICompressor and use Google Closure compiler, which is to much work atm for me and not on my highest priority.

**Comment by Chris2011** [comment]
I tested it, with my new version 2.3.0.

Testcode:
```javascript
let myvar = 'world';
const test = `blaaaa ${myvar}`;
var foo = `ola`;
```

Output:
```javascript
'use strict';let myvar="world";const test=`blaaaa ${myvar}`;var foo="ola";
```

**Comment by Chris2011** [comment]
Will release the new version soon.
